spring.application.name=dashboard-afazio

spring.datasource.url=jdbc:postgresql://localhost:5433/dashboard_afazio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
